[package]
name = "TCP_server"
version = "0.1.0"
authors = ["Junwei <qq971655401@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
